# Generated by Django 2.1.1 on 2018-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('dev_name', models.CharField(max_length=255)),
                ('icon_url', models.URLField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dev_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppSearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255, unique=True)),
                ('apps', models.ManyToManyField(to='gpscraper.AppData')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
